version: '3.8'

services:
  node:
    image: node:18
    container_name: laravel_node
    working_dir: /app
    volumes:
      - ./:/app
    command: sh -c "npm install && npm run dev"
    ports:
      - "5173:5173"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    working_dir: /app
    volumes:
      - ./:/app
    depends_on:
      - db
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: laravel
      DB_USERNAME: laravel
      DB_PASSWORD: laravel
    command: php artisan serve --host=0.0.0.0 --port=8000
    ports:
      - "8000:8000"

  db:
    image: postgres:15
    container_name: laravel_pgsql
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: laravel
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
